# Sets default memory used for gradle commands. Can be overridden by user or command line properties.
# This is required to provide enough memory for the Minecraft decompilation process.
org.gradle.jvmargs=-Xmx3G
org.gradle.daemon=false

## Mod Properties
mod_id=harderspawners
mod_group=com.mactso.harderspawners
mod_version=61.29.0
archive_name=forge-HarderSpawners
# Minecraft & Forge versions
mc_version = 1.21.11
forge_version=61.0.5
mappings_channel=official
mappings_version=1.21.11
