# Done to increase the memory available to gradle.
org.gradle.jvmargs=-Xmx2G
org.gradle.parallel=true
org.gradle.daemon=false

# Fabric Properties
minecraft_version=1.21.10
yarn_mappings=1.21.10+build.3
loader_version=0.18.0
loom_version=1.15-SNAPSHOT

# Mod Properties
	mod_version = 0.31.3
	maven_group = com.mactso.harderSpawners
	archives_base_name = fabric-21.10-harderspawners-CC

# Dependencies
fabric_api_version=0.138.4+1.21.10
fabric.loom.run.username=dev
