modLoader="javafml"
loaderVersion="[61,)"
license="MIT"

[[mods]]
modId="harderspawners"
version="61.7.0"
displayName="Harder Spawners Mod"
displayURL="https://www.curseforge.com/minecraft/mc-mods/harder-spawners"

logoFile="Logo.png"
authors="MacTso, Lupicus"
description='Harder Spawners Mod.'
[[dependencies.harderspawners]]
modId="forge"
mandatory=true
versionRange="[61,)"
ordering="NONE"
side="BOTH"

[[dependencies.harderspawners]]
modId="minecraft"
mandatory=true
versionRange="[1.21.11,1.22)"
ordering="NONE"
side="BOTH"
# side="BOTH", "CLIENT?", "SERVER"